-- M2B: seed remaining MurabacApps portfolio projects (from Design Ref + local product folders)
-- Run after 20260927000011_worldwide_positioning.sql
-- Skips tooling/learning folders (ASP.NET, Blazor, Flutter samples, M2B site itself, etc.)

insert into m2b.projects (
  slug, title, tagline, description, category, work_category, sector, status, outcome,
  stack, client_name, year, cover_image_url, logo_url, mesh_preview, mesh_category,
  accent_color, stack_line, is_featured, is_published, sort_order,
  show_in_hero, show_in_bento, bento_sort_order
)
values
  (
    'muuqwear',
    'MuuqWear',
    'Modern apparel commerce with tier-based influencer payouts and live chat.',
    'High-performance storefront powered by a .NET API backend — affiliate tracking, tiered commissions, ZAAD checkout, and customer size advisories.',
    'website_ecommerce', 'commerce', 'E-Commerce & Affiliates', 'Live',
    'Increased influencer-driven conversion by 210% within 90 days.',
    '[".NET 8 C#","Next.js","SQL Server","Tailwind","ZAAD"]'::jsonb,
    'Muuq Fashion Brands', 2025,
    '/projects/muuqwear-logo.png', '/projects/muuqwear-logo.png',
    'Affiliate · ZAAD · Live Chat', 'Fashion Commerce', '#D4AF37',
    '.NET · Next.js · ZAAD', false, true, 20, false, true, 20
  ),
  (
    'maqal',
    'Maqal Audiobooks',
    'Horn literature & audiobook platform with cross-device bookmarking and offline cache.',
    'Audio streaming architecture engineered for intermittent 3G networks — chapter indexing, signed audio tokens, sleep timers, and local author royalties.',
    'web_app', 'faith', 'Media & Literature', 'Live',
    'Streamed 1.2 million minutes of Somali literature and historical memoirs.',
    '["React","Howler.js","Cloudflare Workers","Laravel"]'::jsonb,
    'Maqal Publishing', 2025,
    null, null,
    'Offline Cache · 3G Edge', 'Sacred Audio', '#0A3A7A',
    'React · Laravel · Workers', false, true, 21, false, true, 21
  ),
  (
    'gaarx',
    'GaarX / Gadogaari',
    'Automotive sales ecosystem: customer portal, dealership inventory, and valuation API.',
    'Marketplace with verified inspection badges, WhatsApp dealer contact, USD/SLS currency switching, and import duty calculator for port shipments.',
    'website_ecommerce', 'commerce', 'Automotive Commerce', 'Live',
    'Over 1,800 active vehicle listings across regional hubs.',
    '["Next.js","TypeScript","Tailwind","Laravel","MySQL"]'::jsonb,
    'Horn Automotive Exchange', 2025,
    '/projects/gaarx-logo.png', '/projects/gaarx-logo.png',
    'Listings · Duty Calc · Dealers', 'Auto Marketplace', '#0B2F6B',
    'Next.js · Laravel · MySQL', false, true, 22, false, true, 22
  ),
  (
    'acu',
    'Acceptance and Change University (ACU)',
    'University digital presence, faculty CMS, and student admissions portal.',
    'Academic institution portal with program catalogs, research publications, campus events, and student registration intake.',
    'website_ecommerce', 'websites', 'Higher Education', 'Live',
    'Modernized enrollment with a 40% increase in digital prospectus downloads.',
    '["Next.js","Tailwind","CMS","Bilingual EN/SO"]'::jsonb,
    'ACU Higher Education', 2025,
    '/projects/acu-logo.png', '/projects/acu-logo.png',
    'Admissions · Programs · CMS', 'Higher Ed', '#0A3A7A',
    'Next.js · CMS · Bilingual', false, true, 23, false, false, 0
  ),
  (
    'acfh',
    'ACFH (Acceptance & Change for Health)',
    'Public health NGO platform for mental-health research, training, and clinical reports.',
    'Bilingual health knowledge base and donor engagement portal for medical publications, psychosocial training, and clinical outreach stats.',
    'website_ecommerce', 'websites', 'Non-Profit & Health', 'Live',
    'Empowered practitioners with digital clinical guidelines across 4 hospitals.',
    '["React","Tailwind","Headless CMS"]'::jsonb,
    'ACFH Health NGO', 2025,
    '/projects/acfh-logo.png', '/projects/acfh-logo.png',
    'Research · Training · Donors', 'Health NGO', '#0B2F6B',
    'React · CMS · Accessibility', false, true, 24, false, false, 0
  ),
  (
    'garaad-agri',
    'Garaad Agri',
    'Arid-zone farming research, climate crop advisories, and publications library.',
    'Scientific editorial platform for yield data, drip irrigation protocols, soil health analyses, and seasonal farmer calendar recommendations.',
    'website_ecommerce', 'websites', 'Agriculture & Science', 'Live',
    'Disseminated 30+ peer-reviewed dryland agronomy papers.',
    '["Astro","React","Tailwind","Markdown"]'::jsonb,
    'Garaad Agricultural Research', 2025,
    '/projects/garaad-agri-cover.jpg', '/projects/garaad-agri-cover.jpg',
    'Research · Advisories · Library', 'Agri Science', '#D4AF37',
    'Astro · React · Markdown', false, true, 25, false, false, 0
  ),
  (
    'mire-farms',
    'Mire Farms',
    'Heritage farm brand story, organic greenhouse produce, and wholesale inquiries.',
    'Visual brand experience from soil to market tables — product varieties, wholesale contacts, and sustainability practices.',
    'website_ecommerce', 'websites', 'Agriculture & Logistics', 'Live',
    'Established direct farm-to-supermarket wholesale channels.',
    '["Next.js","Tailwind","Framer Motion","WhatsApp"]'::jsonb,
    'Mire Agro-Enterprise', 2025,
    '/projects/mire-farms-cover.jpg', '/projects/mire-farms-cover.jpg',
    'Wholesale · Brand Story', 'Agri Brand', '#0B2F6B',
    'Next.js · WhatsApp Commerce', false, true, 26, false, false, 0
  ),
  (
    'qb-legal',
    'QB Legal Partners',
    'Law firm website in royal navy & gold with interactive practice areas.',
    'Corporate site for FDI counsel, maritime law, commercial arbitration, and corporate compliance.',
    'website_ecommerce', 'websites', 'Legal & Corporate', 'Live',
    'Secured international enterprise inquiries for commercial arbitration.',
    '["React","Motion","Tailwind","Bilingual EN/SO"]'::jsonb,
    'QB Legal Advocates & Consultants', 2025,
    '/projects/qb-legal-logo.png', '/projects/qb-legal-logo.png',
    'Practice Areas · Counsel', 'Legal', '#D4AF37',
    'React · Motion · Bilingual', false, true, 27, false, false, 0
  ),
  (
    'carnexa',
    'Carnexa Automotive',
    'Automotive warranty and vehicle diagnostics platform launch experience.',
    'High-conversion waitlist experience with vehicle registration, fleet teasers, and partner dealership onboarding.',
    'website_ecommerce', 'websites', 'Automotive & Tech', 'Coming Soon',
    'Generated 2,400+ verified driver registrations ahead of deployment.',
    '["React","Tailwind","Interactive Configurator"]'::jsonb,
    'Carnexa Mobility', 2025,
    '/projects/carnexa-logo.png', '/projects/carnexa-logo.png',
    'Waitlist · Diagnostics', 'Auto Tech', '#0A3A7A',
    'React · Tailwind', false, true, 28, false, false, 0
  ),
  (
    'liby-foundation',
    'Liby Foundation & ACHealth',
    'Humanitarian program monitoring, maternal clinic support, and grant audits.',
    'Program operations dashboard and donor portal for regional health and education initiatives with field expense reconciliation.',
    'web_app', 'operations', 'Humanitarian & Aid', 'Live',
    'Audited and verified 40 community health posts with photographic evidence chains.',
    '["Next.js","Tailwind","Audit Modules"]'::jsonb,
    'Liby Humanitarian Foundation', 2025,
    '/projects/liby-foundation-cover.jpg', '/projects/liby-foundation-cover.jpg',
    'Grants · Clinics · Audits', 'Humanitarian', '#0B2F6B',
    'Next.js · Financial Audit', false, true, 29, false, false, 0
  ),
  (
    'import-dispatch',
    'Customs & Port Dispatch Engine',
    'Cross-border cargo manifest clearance, truck dispatching, and container tracking.',
    'Real-time logistics clearing platform linking customs manifests with haulage fleets and inland bonded warehouses.',
    'erp', 'operations', 'Logistics & Customs', 'In Production',
    'Reduced truck dwell time at customs check-posts by 4.5 hours on average.',
    '["Laravel","Filament","MySQL","GPS Webhooks"]'::jsonb,
    'Regional Logistics Consortium', 2025,
    '/projects/import-dispatch-logo.png', '/projects/import-dispatch-logo.png',
    'Manifests · Fleets · GPS', 'Port Ops', '#0A3A7A',
    'Laravel · Filament · GPS', false, true, 30, false, true, 30
  ),
  (
    'salguri',
    'Salguri Business Ops',
    'POS, multi-warehouse stock replenishment, and credit ledger for local retail.',
    'Built for local merchant realities: barcode scanning, customer debt books (deyn ledger), and ZAAD merchant payment reconciliation.',
    'erp', 'operations', 'Retail & Inventory', 'Live',
    'Eliminated daily stock discrepancy across 6 retail branches.',
    '["Flutter Desktop","SQLite","Cloud Sync API"]'::jsonb,
    'Salguri Commercial Enterprises', 2025,
    null, null,
    'POS · Deyn Ledger · ZAAD', 'Retail Ops', '#0B2F6B',
    'Flutter · SQLite · Sync', false, true, 31, false, true, 31
  ),
  (
    'taalo',
    'Taalo',
    'Modern product experience engineered in the M2B studio stack.',
    'Studio-built web product from the Taalo codebase — polished UI, production-ready Next.js delivery.',
    'web_app', 'websites', 'Studio Product', 'Studio Product',
    'Shipped as a polished production web experience.',
    '["Next.js","TypeScript","Tailwind"]'::jsonb,
    'M2B Studio', 2025,
    '/projects/taalo-logo.png', '/projects/taalo-logo.png',
    'Studio Product', 'Web Product', '#D4AF37',
    'Next.js · TypeScript', false, true, 32, false, false, 0
  )
on conflict (slug) do update set
  title = excluded.title,
  tagline = excluded.tagline,
  description = excluded.description,
  category = excluded.category,
  work_category = excluded.work_category,
  sector = excluded.sector,
  status = excluded.status,
  outcome = excluded.outcome,
  stack = excluded.stack,
  client_name = excluded.client_name,
  year = excluded.year,
  cover_image_url = coalesce(excluded.cover_image_url, m2b.projects.cover_image_url),
  logo_url = coalesce(excluded.logo_url, m2b.projects.logo_url),
  mesh_preview = excluded.mesh_preview,
  mesh_category = excluded.mesh_category,
  accent_color = excluded.accent_color,
  stack_line = excluded.stack_line,
  is_published = excluded.is_published,
  sort_order = excluded.sort_order,
  show_in_bento = excluded.show_in_bento,
  bento_sort_order = excluded.bento_sort_order,
  updated_at = now();
